version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=vigilante_virtual
            - DB_USERNAME=grupo3
            - DB_PASSWORD=grupo3

    db:
        image: postgres:16
        container_name: postgres_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: vigilante_virtual
            POSTGRES_USER: grupo3
            POSTGRES_PASSWORD: grupo3
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
